### ISSUE TITLE
Não foi possível instalar

### ISSUE THREAD

**Issue by lubien** [fiote/pocketTactics-apk#1]
Desconheço o motivo
http://i.imgur.com/nE2WquD.jpg

**Comment by lubien** [comment]
Informações do celular
![Info](http://i.imgur.com/MNxdbHa.jpg)

**Comment by fiote** [comment]
@lubien, obrigado pela informação! Então, existem duas versões do APK, que se não me engano são direcionadas a processadores diferentes (variando então de modelo pra modelo). Você já tentou com as duas? Olha lá https://github.com/fiote/pocketTactics-apk/releases

**Comment by lubien** [comment]
Estou baixando aqui, a internet que n ajuda muito hehe.
Enquanto isso, o que você acha de focar em um PWA ao invés de um app?

**Comment by fiote** [comment]
O que seria um PWA? De qualquer forma, adianto que o jogo também vai ter uma versão via browser ;)

**Comment by lubien** [comment]
Primeiramente, funcionou a outra versao. Não havia visto porque baixei o link que estava em fftonline.net. Aproveitando pra dizer que o site não consegue ser carregado se eu não desativar o javascript ^^

PWA são Progressive Web Apps. Basicamente, sites "instaláveis" com capacidades como fazer cache do conteúdo deles (JS, CSS, HTML, JSON...) de forma que é possível utilizar offline também. PWAs tão ganhando bastante destaque entre diversas empresas famosas recentemente.

[Getting started with Progressive Web Apps](https://addyosmani.com/blog/getting-started-with-progressive-web-apps/)

* Funciona em browser
* É "instalável" em dispositivos móveis sem ter que fazer uma build pra cada OS.
* Estático (pode hospedar no GitHub)
* E outras... hehe

**Comment by fiote** [comment]
Valeu pelo toque! Problema resolvido então ;) Só me fala qual é o seu celular/versão do android pra eu adicionar na lista ^^

**Comment by lubien** [comment]
Ta na foto ai em cima, Lenovo A7 hehe. Devo criar uma issue sobre o problema no JS do site?

**Comment by fiote** [comment]
Não lol, esquece o site por enquanto xD.
