### ISSUE TITLE
Unidade morta após a batalha

### ISSUE THREAD

**Issue by filipefrozza** [fiote/pocketTactics-apk#12]
Quando uma unidade minha morre em batalha, e eu entro em uma batalha dps, a mesma continua morta.

**Comment by fiote** [comment]
Nossa, um erro mais random que o outro UIAEHUAIEIUEHA. Talvez seja por isso que as unidades passam o turno automaticamente as vezes. CARAMBA FILIPE, acho que você me salvou de achar um erro que ia demorar horas pra achar lol

**Comment by filipefrozza** [comment]
Capaz o/ no que puder eu vou estar ajudando

**Comment by fiote** [comment]
Resolvido (server-side).
