### ISSUE TITLE
Reset dos Turnos dos oponentes

### ISSUE THREAD

**Issue by Deivilan** [fiote/pocketTactics-apk#14]
Tem um bug de quando você começa a batalha, vem os 3 turnos seguidos do seu oponente, e eles ficam se resetando sem as unidades dele fazerem nada, como se ficasse apertando pra passar a vez infinitamente pra você, só que você não age, fica só nos turnos dele.

**Comment by fiote** [comment]
Duplicado do https://github.com/fiote/pocketTactics-apk/issues/12, finalizado.
