### ISSUE TITLE
Bug no ranked em que um jogador não entra na partida

### ISSUE THREAD

**Issue by Gabagabagaba** [fiote/pocketTactics-apk#29]
![sem titulo](https://cloud.githubusercontent.com/assets/20630605/17152194/34b11d56-534d-11e6-8f7d-decba2d23e6c.png)

**Comment by Gabagabagaba** [comment]
Para um dos jogadores aparece apenas os seus personagens e para o outro não aparece nenhum personagem

**Comment by Gabagabagaba** [comment]
Aparentemente o bug ocorre se duas partidas ocorrem ao mesmo tempo, onde a segunda partida a começar buga.

**Comment by Gabagabagaba** [comment]
Bug encontrado com a ajuda de Groder, Graf e Iangrel.

**Comment by fiote** [comment]
Resolvido (server-side).
