### ISSUE TITLE
Logout inesperado

### ISSUE THREAD

**Issue by lubien** [fiote/pocketTactics-apk#3]
De tempos em tempos, até mesmo durante batalhas, a tela pisca algumas vezes e volto para a tela de login

**Comment by fiote** [comment]
Quando o servidor cai, ou você é desconectado por algum erro do servidor, você volta pra tela do login. 
Caso o servidor ainda não esteja online, a tela vai piscar (porque tá dando um refresh) e vai tentar de novo. Infelizmente isso vai acontecer ainda por um tempo :\

**Comment by lubien** [comment]
Entendo. 

Aproveitando, tem algum chat tipo gitter onde os jogadores podem conversar entre si? Além do grupo no facebook, só pra n ficar no escuro mesmo

**Comment by fiote** [comment]
Vou ver se crio um discord pra isso ;)

**Comment by fiote** [comment]
https://discord.gg/m6HxkdM Feito.
