### ISSUE TITLE
Movimento não atualiza entre combates

### ISSUE THREAD

**Issue by Gabagabagaba** [fiote/pocketTactics-apk#33]
Se uma unidade se mover no ultimo turno de um combate (move e mata o ultimo oponente) ela não tem pontos de movimento no próximo combate

**Comment by Gabagabagaba** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/20630605/17159785/81c3034c-5376-11e6-84f6-95aec67e9c9a.png)

**Comment by Gabagabagaba** [comment]
Bonus: As setinhas estão meio desalinhadas:
![sem titulo](https://cloud.githubusercontent.com/assets/20630605/17160419/3426b6b0-537b-11e6-9556-27177bbacbe2.png)

**Comment by fiote** [comment]
Resolvido (server-side).
