### ISSUE TITLE
Derrota Instantanea

### ISSUE THREAD

**Issue by DWoonD** [fiote/pocketTactics-apk#37]
Segunda vez que acontece comigo estou no meio da batalha normal, ai do nada eu perco, a primeira vez achei que fosse limite de turnos, mas a segunda foi bem no começo, e seria uma batalha que eu ganharia, nos dois casos em que aconteceu. No segundo estava com a magia de cura que ia causar dano, mas aparentemente mostrou que curaria o inimigo, e ai apareceu do nada derrota, antes de eu clicar em nada.

Outro detalhe, depois que acontece a derrota eu não consigo mais batalhar no pvp normal com mais ninguém, eu aceito mas a tela não carrega e nada acontece, ai tenho que dar um refresh

**Comment by fiote** [comment]
Tá aqui no log haha (GMT-4)

```
=============================================================
14:37:23 dwoond #8
14:37:23 --------------------------------------------------------------
14:37:23 {"battle_id":5132,"battle_mode":"players","event":"update_values_skill","skill_id":5332,"unit_id":400,"card_id":null,"target_id":409}
14:37:23 Missing error handler on `socket`.
14:37:23 TypeError: Cannot set property 'multiplier' of null
```
Isso te desconectou do servidor, mas o client ficou 'on'. É por isso que não conseguiu batalhar mais antes de logar novamente. 

Dito isso, resolvi o problema em questão ;)
