### ISSUE TITLE
Erro de cálculo de gold

### ISSUE THREAD

**Issue by DWoonD** [fiote/pocketTactics-apk#39]
Então não sei se é erro de somar quando se ganha e mostrar o total de forma correta ou se é erro na hora da compra mesmo.
Caso eu tinha acho que 85 ou 94 de gold não me lembro ao certo ai comprei um pack de guerreiro e depois da compra meu dinheiro meio que foi pra 118.

Eu acho que isso aconteceu uma vez quando comprei itens também, porém como eu não prestei muito atenção eu não sei detalhar, mas eu lembro que daria pra comprar um item, pois eu tinha menos de 70 de gold, e depois que comprei um deu pra comprar outro, ou seja, depois da compra meu gold calculou de uma forma que me deu mais gold

**Comment by fiote** [comment]
Resolvido. Valeu! As batalhas estavam dando o valor em moedas duas vezes (apesar que não atualiza o client na segunda vez, aí quando você comprava ele atualizava).
