### ISSUE TITLE
Bonus dos itens durante as batalhas

### ISSUE THREAD

**Issue by fiote** [fiote/pocketTactics-apk#7]
A barra de HP não está exibindo corretamente os valores caso o personagem em questão esteja com itens que aumentem o HP. Os valores de ataque também estão esquisitos as vezes.

**Comment by Gabagabagaba** [comment]
![screenshot_2016-07-24-19-40-52](https://cloud.githubusercontent.com/assets/20630605/17087010/abe9e2c2-51d6-11e6-94f2-8c4f5d5da6a2.png)

**Comment by fiote** [comment]
Problema das unidades com ataque negativo resolvido.

**Comment by fiote** [comment]
Problema dos bonus de HP não sendo aplicado resolvido.
